/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/**/*.{ts,tsx}',
    '!./docs/**/*' // Exclude documentation files from Tailwind processing
  ],
  theme: {
    extend: {
      colors: {
        'brand-a': '#38ae8e',
        'brand-b': '#0b9b75',
        'brand-c': '#086049',
        'brand-d': '#ffa200',
        'brand-e': '#ffde00',
        'brand-f': '#8d8d8d',
        'brand-g': '#a90000',
        'brand-h': '#5a497f',
        'brand-i': '#f6e9d2',
        'brand-j': '#e1c116',
        'brand-k': '#48484a',
        'brand-l': '#29272a',
        'brand-m': '#101011',
        'brand-n': '#9886bf',
        'brand-p': '#086149',
        'brand-q': '#f3f3f3',
        'brand-r': '#0A8564',
        'brand-s': '#E1B500',
        'gmmc-green': '#3eaca7',
        'gmmc-blue': '#005461',
        'big-change-a': '#fff77a',
        'big-change-b': '#404241',
        'change-liverpool': '#8b201d',
        'cia-yellow': '#f8c77c',
        'just-giving': '#AD29B6',
        'money-matters-background': '#52599d',
        'money-matters-text': '#eacc1c',
        'soton-giving': '#5d4567',
        'street-change-glasgow': '#201751',
        'street-aid-yellow': '#ffcf06',
        'street-aid-orange': '#f5821f',
        'sea-blue': '#00A6B0',
        'vfg-orange': '#ffb533',
        'wmht-hero-lilac': '#796e78',
        'wmht-lilac': '#534b53',
        'wmht-orange': '#e57b2b',
        'wmht-grey': '#515151',
      },
      spacing: {
        'base-font-size': '1.0rem',
        'border-radius': '0.625rem',
        'border-radius-small': '0.3125rem',
        'header-top': '7.3125rem',
        'header-height': '2.625rem',
        'header-margin': '2.75rem',
        'header-subnav-height': '5.3125rem',
        'header-subnav-margin': '5.3125rem',
      },
      height: {
        'screen-header': 'calc(100vh - 4rem)',
      },
    },
  },
  plugins: [],
};